name: pokemon
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  equatable: ^2.0.5
  dio: ^5.2.0
  infinite_scroll_pagination: ^3.2.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/pokemon.png



  fonts:
    - family: ClashDisplay
      fonts:
        - asset: assets/font/ClashDisplay-Bold.otf
          weight: 700
        - asset: assets/font/ClashDisplay-Light.otf
          weight: 300
        - asset: assets/font/ClashDisplay-Medium.otf
          weight: 500
        - asset: assets/font/ClashDisplay-Regular.otf
          weight: 400
        - asset: assets/font/ClashDisplay-SemiBold.otf
          weight: 600
