name: pokemon
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: ClashDisplay
      fonts:
        - asset: assets/font/ClashDisplay-Bold.otf
          weight: 700
        - asset: assets/font/ClashDisplay-Light.otf
          weight: 300
        - asset: assets/font/ClashDisplay-Medium.otf
          weight: 500
        - asset: assets/font/ClashDisplay-Regular.otf
          weight: 400
        - asset: assets/font/ClashDisplay-SemiBold.otf
          weight: 600
